### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by raichophp** [raichophp/rkstyle.info#1]

**Comment by nitincoded** [comment]
Change:
`echo 'hello';`
to:
`return 'hello';`

**Comment by raichophp** [comment]
same

**Comment by nitincoded** [comment]
Do you get the default Laravel page with http://localhost ?

**Comment by raichophp** [comment]
yes

**Comment by raichophp** [comment]
'url' => env('APP_URL', 'http://localhost'),
